#!/usr/bin/env python3
"""Render docs/features.md from the feature availability manifest."""

from __future__ import annotations

import argparse
import json
import sys
from collections import OrderedDict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "data" / "feature-availability.json"
OUTPUT = ROOT / "docs" / "features.md"

REQUIRED_TOP_LEVEL = {"schema_version", "updated", "version_floor", "intro", "labels", "features"}
REQUIRED_FEATURE_FIELDS = {"area", "capability", "oss", "pro", "notes"}
FORBIDDEN_GENERATED_PATTERNS = (
    ("All features", "FREE"),
    ("Auto", "failover", "backup providers"),
    ("Semantic equivalence", "guaranteed"),
)


def _escape_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def load_manifest(path: Path = MANIFEST) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        manifest = json.load(handle)

    missing = REQUIRED_TOP_LEVEL - set(manifest)
    if missing:
        raise ValueError(f"{path} missing top-level fields: {', '.join(sorted(missing))}")

    labels = manifest["labels"]
    if not isinstance(labels, dict) or not labels:
        raise ValueError("labels must be a non-empty object")

    features = manifest["features"]
    if not isinstance(features, list) or not features:
        raise ValueError("features must be a non-empty list")

    known_labels = set(labels)
    for index, feature in enumerate(features, start=1):
        missing_fields = REQUIRED_FEATURE_FIELDS - set(feature)
        if missing_fields:
            raise ValueError(f"feature {index} missing fields: {', '.join(sorted(missing_fields))}")
        if feature["oss"] not in known_labels and feature["oss"] not in {"Not included"}:
            raise ValueError(f"feature {index} has unknown OSS label: {feature['oss']}")
        if feature["pro"] not in known_labels and feature["pro"] not in {
            "Not required",
            "Optional extensions",
            "Not promised",
        }:
            raise ValueError(f"feature {index} has unknown Pro label: {feature['pro']}")

    return manifest


def render(manifest: dict) -> str:
    lines: list[str] = [
        "---",
        'title: "Feature Matrix"',
        'created: 2026-03-24T19:05:55Z',
        f"updated: {manifest['updated']}",
        "---",
        "<!-- Generated by scripts/render_feature_matrix.py from data/feature-availability.json. -->",
        "",
        "# Feature Matrix",
        "",
        str(manifest["intro"]),
        "",
        f"Current OSS beta floor: v{manifest['version_floor']}.",
        "",
        "## Availability labels",
        "",
        "| Label | Meaning |",
        "|---|---|",
    ]

    for label, meaning in manifest["labels"].items():
        lines.append(f"| {_escape_cell(label)} | {_escape_cell(meaning)} |")

    by_area: OrderedDict[str, list[dict]] = OrderedDict()
    for feature in manifest["features"]:
        by_area.setdefault(feature["area"], []).append(feature)

    for area, features in by_area.items():
        lines.extend(
            [
                "",
                f"## {area}",
                "",
                "| Capability | OSS beta | Pro | Notes |",
                "|---|---|---|---|",
            ]
        )
        for feature in features:
            lines.append(
                "| {capability} | {oss} | {pro} | {notes} |".format(
                    capability=_escape_cell(feature["capability"]),
                    oss=_escape_cell(feature["oss"]),
                    pro=_escape_cell(feature["pro"]),
                    notes=_escape_cell(feature["notes"]),
                )
            )

    lines.extend(
        [
            "",
            "## Boundary notes",
            "",
            "- Requests still go to the model provider you configure; TokenPak does not run a hosted model service for the OSS beta.",
            "- Savings depend on workload, provider pricing, and cache eligibility. Use local status and savings commands for attribution.",
            "- Pro-only rows are not part of the Apache 2.0 OSS beta surface.",
            "",
        ]
    )
    rendered = "\n".join(lines)

    for pattern in FORBIDDEN_GENERATED_PATTERNS:
        if all(part in rendered for part in pattern):
            raise ValueError(f"generated output contains forbidden stale claim pattern: {pattern!r}")

    return rendered


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if docs/features.md is not up to date")
    args = parser.parse_args()

    try:
        rendered = render(load_manifest())
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is not generated from {MANIFEST.relative_to(ROOT)}", file=sys.stderr)
            return 1
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
